### ISSUE TITLE
2018/06/27

### ISSUE THREAD

**Issue by Jesonhu** [Jesonhu/...#39]
## Todo-List
修改项目：
- [x] 语言.5.故事屋.爱笑的妹妹
- [x] 语言.5.故事屋.西西的漂流瓶
- [x] 语言.5.故事屋.后羿射日
- [x] 语言.5.故事屋.古立的新同学
- [x] 语言.5.认一认.今天我要一个人睡
- [x] 语言.5.认一认.爱笑的妹妹

**Comment by Jesonhu** [comment]
## 上午

## 下午

## 晚上
